BusPasajes/Models/Marca.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusPasajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDMARCA { get; set; }
        public string NOMBRE { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

BusPasajes/Controllers/MarcaController.cs
using BusPasajes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Management.Instrumentation;
using System.Web;
using System.Web.Mvc;

namespace BusPasajes.Controllers
{
    public class MarcaController : Controller
    {
        // GET: Marca
        public ActionResult Index()
        {
            List<MarcaCLS> lstmarca = null;
            using (var bd = new BDPasajeEntities())
            {
                lstmarca = (from marca in bd.Marca
                            where marca.BHABILITADO == 1
                            select new MarcaCLS
                            {
                                iidmarca = marca.IIDMARCA,
                                nombre = marca.NOMBRE,
                                descripcion = marca.descripcion
                            }).ToList();
            }
            return View(lstmarca);
        }

        public ActionResult Agregar()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(MarcaCLS oMarcaCLS)
        {
            if (!ModelState.IsValid)
            {
                return View(oMarcaCLS);
            }
            else
            {
                using (var bd = new BDPasajeEntities())
                {
                    Marca oMarca = new Marca();
                    oMarca.NOMBRE = oMarcaCLS.nombre;
                    oMarca.descripcion = oMarcaCLS.descripcion;
                    oMarca.BHABILITADO = 1;
                    bd.Marca.Add(oMarca);
                    bd.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

BusPasajes/Views/Marca/Agregar.cshtml
@using BusPasajes.Models;
@model MarcaCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Marca", FormMethod.Post))
            {
                <div>
                    @Html.LabelFor(p => p.nombre)
                    @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" }) 
                    @Html.ValidationMessage("nombre", new { @class = "text-danger"})
                </div>
                <div>
                    @Html.LabelFor(p => p.descripcion)
                    @Html.TextBoxFor(p => p.descripcion, new { @class = "form-control"})
                    @Html.ValidationMessage("descripcion", new { @class = "text-danger"})
                </div>

                <br />

                <div style="margin: auto">
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </div>
            }
    </div>
</div>

BusPasajes/Views/Marca/Index.cshtml
@using BusPasajes.Models;
@model List<MarcaCLS> 
@{
    ViewBag.Title = "Index";
}

<h2>Marca</h2>
@Html.ActionLink("Agregar", "Agregar", "Marca", null, new { @class = "btn btn-primary"})
<br />
<br />

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td width="10%"># de Marca</td>
            <td width="20%">Nombre Marca</td>
            <td width="70%">Descripcion</td>
            @* //TOMA EL DISPLAY QUE SE TIENE DENTRO DE LA CLASE Y LO MARCA EN LA VISTA
            <td width="10%">@Html.LabelFor(p => Model[0].iidmarca)</td>
            <td width="20%">@Html.LabelFor(p => Model[0].nombre)</td>
            <td width="70%">@Html.LabelFor(p => Model[0].descripcion)</td>
            *@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidmarca</td>
                    <td>@item.nombre</td>
                    <td>@item.descripcion</td>
                </tr>
            }
    </tbody>
</table>