BusPasajes/Models/Sucursal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusPasajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sucursal()
        {
            this.Bus = new HashSet<Bus>();
        }
    
        public int IIDSUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> FECHAAPERTURA { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bus> Bus { get; set; }
    }
}

BusPasajes/Controllers/SucursalController.cs
using BusPasajes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BusPasajes.Controllers
{
    public class SucursalController : Controller
    {
        // GET: Sucursal
        public ActionResult Index()
        {
            List<SucursalCLS> lstsucursal = null;
            using (var bd = new BDPasajeEntities())
            {
                lstsucursal = (from sucursal in bd.Sucursal
                               where sucursal.BHABILITADO == 1
                              select new SucursalCLS
                              {
                                  iidsucursal = sucursal.IIDSUCURSAL,
                                  nombre = sucursal.NOMBRE,
                                  direccion = sucursal.DIRECCION,
                                  telefono = sucursal.TELEFONO,
                                  email = sucursal.EMAIL
                              }).ToList();
            }
            return View(lstsucursal);
        }

        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Agregar(SucursalCLS oSucursalCLS)
        {
            if (!ModelState.IsValid)
            {
                return View (oSucursalCLS);
            }
            else
            {
                using (var bd = new BDPasajeEntities())
                {
                    Sucursal oSucursal = new Sucursal();
                    oSucursal.NOMBRE = oSucursalCLS.nombre;
                    oSucursal.DIRECCION = oSucursalCLS.direccion;
                    oSucursal.TELEFONO = oSucursalCLS.telefono;
                    oSucursal.EMAIL = oSucursalCLS.email;
                    oSucursal.FECHAAPERTURA = oSucursalCLS.fechaapertura;
                    oSucursal.BHABILITADO = 1;
                    bd.Sucursal.Add(oSucursal);
                    bd.SaveChanges();
                }
            }
            return RedirectToAction("Index"); 
        }
    }
}

BusPasajes/Views/Sucursal/Agregar.cshtml
@using BusPasajes.Models;
@model SucursalCLS
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Agregar", "Sucursal", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(p => p.nombre)
                @Html.TextBoxFor(p => p.nombre, new { @class = "form-control" })
                @Html.ValidationMessage("nombre", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.direccion)
                @Html.TextBoxFor(p => p.direccion, new { @class = "form-control" })
                @Html.ValidationMessage("direccion", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.telefono)
                @Html.TextBoxFor(p => p.telefono, new { @class = "form-control" })
                @Html.ValidationMessage("telefono", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.email)
                @Html.TextBoxFor(p => p.email, new { @class = "form-control" })
                @Html.ValidationMessage("email", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.fechaapertura)
                @Html.EditorFor(p => p.fechaapertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("fechaapertura", new { @class = "text-danger"})
            </div>
            
            <br />

            <div style="margin: auto">
                <input type="submit" class="btn d-block btn-primary" value="Guardar" />
            </div>
        }
    </div>
</div>

BusPasajes/Views/Sucursal/Index.cshtml
@using BusPasajes.Models;
@model List<SucursalCLS>
@{
    ViewBag.Title = "Index";
}

<h2>Sucursal</h2>
@Html.ActionLink("Agregar", "Agregar", "Sucursal", null, new { @class = "btn btn-primary"})
<br />
<br />

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td># de Sucursal</td>
            <td>Nomnbre Sucursal</td>
            <td>Dirección</td>
            <td>Telefono Sucursal</td>
            <td>Email</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
            {
                <tr>
                    <td>@item.iidsucursal</td>
                    <td>@item.nombre</td>
                    <td>@item.direccion</td>
                    <td>@item.telefono</td>
                    <td>@item.email</td>
                </tr>
            }
    </tbody>
</table>